# Generated by Django 2.2.5 on 2020-03-03 21:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200227_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='aprroved_comment',
            new_name='approved_comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 21, 7, 49, 354787, tzinfo=utc)),
        ),
    ]
